In [49]:
import pandas as pd
import numpy as np

In [50]:
df = pd.read_csv('Train.csv')
df

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [51]:
df.head(5)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [52]:
df.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [54]:
df.shape

(8523, 12)

In [55]:
df.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [56]:
for column in df.columns:
    if df[column].dtype == 'object':
        mode_value = df[column].mode()[0]
        df[column].fillna(mode_value, inplace=True)

In [57]:
df['Item_Weight'] = df['Item_Weight'].fillna(df['Item_Weight'].mean())

In [58]:
df.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [59]:
df.nunique()

Item_Identifier              1559
Item_Weight                   416
Item_Fat_Content                5
Item_Visibility              7880
Item_Type                      16
Item_MRP                     5938
Outlet_Identifier              10
Outlet_Establishment_Year       9
Outlet_Size                     3
Outlet_Location_Type            3
Outlet_Type                     4
Item_Outlet_Sales            3493
dtype: int64

In [60]:
df.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [61]:
x = df[['Item_Fat_Content','Item_Type','Outlet_Identifier','Outlet_Establishment_Year','Outlet_Size','Outlet_Location_Type','Outlet_Type']]

In [62]:
x

,Item_Fat_Content,Item_Type,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,Low Fat,Dairy,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,Regular,Soft Drinks,OUT018,2009,Medium,Tier 3,Supermarket Type2
2,Low Fat,Meat,OUT049,1999,Medium,Tier 1,Supermarket Type1
3,Regular,Fruits and Vegetables,OUT010,1998,Medium,Tier 3,Grocery Store
4,Low Fat,Household,OUT013,1987,High,Tier 3,Supermarket Type1
...,...,...,...,...,...,...,...
8518,Low Fat,Snack Foods,OUT013,1987,High,Tier 3,Supermarket Type1
8519,Regular,Baking Goods,OUT045,2002,Medium,Tier 2,Supermarket Type1
8520,Low Fat,Health and Hygiene,OUT035,2004,Small,Tier 2,Supermarket Type1
8521,Regular,Snack Foods,OUT018,2009,Medium,Tier 3,Supermarket Type2
8522,Low Fat,Soft Drinks,OUT046,1997,Small,Tier 1,Supermarket Type1

In [63]:
x.nunique()

Item_Fat_Content              5
Item_Type                    16
Outlet_Identifier            10
Outlet_Establishment_Year     9
Outlet_Size                   3
Outlet_Location_Type          3
Outlet_Type                   4
dtype: int64

In [64]:
x['Outlet_Identifier'].unique()

array(['OUT049', 'OUT018', 'OUT010', 'OUT013', 'OUT027', 'OUT045',
       'OUT017', 'OUT046', 'OUT035', 'OUT019'], dtype=object)

In [65]:
x['Item_Type'].unique()

array(['Dairy', 'Soft Drinks', 'Meat', 'Fruits and Vegetables',
       'Household', 'Baking Goods', 'Snack Foods', 'Frozen Foods',
       'Breakfast', 'Health and Hygiene', 'Hard Drinks', 'Canned',
       'Breads', 'Starchy Foods', 'Others', 'Seafood'], dtype=object)

In [66]:
x['Outlet_Identifier'].unique()

array(['OUT049', 'OUT018', 'OUT010', 'OUT013', 'OUT027', 'OUT045',
       'OUT017', 'OUT046', 'OUT035', 'OUT019'], dtype=object)

In [67]:
x['Outlet_Establishment_Year'].unique()

array([1999, 2009, 1998, 1987, 1985, 2002, 2007, 1997, 2004], dtype=int64)

In [68]:
x['Outlet_Size'].unique()

array(['Medium', 'High', 'Small'], dtype=object)

In [69]:
x['Outlet_Location_Type'].unique()

array(['Tier 1', 'Tier 3', 'Tier 2'], dtype=object)

In [70]:
x['Outlet_Type'].unique()

array(['Supermarket Type1', 'Supermarket Type2', 'Grocery Store',
       'Supermarket Type3'], dtype=object)

In [71]:
y = df['Item_Outlet_Sales']

In [72]:
y

0       3735.1380
1        443.4228
2       2097.2700
3        732.3800
4        994.7052
          ...
8518    2778.3834
8519     549.2850
8520    1193.1136
8521    1845.5976
8522     765.6700
Name: Item_Outlet_Sales, Length: 8523, dtype: float64

In [73]:
from sklearn.preprocessing import LabelEncoder

In [74]:
Fat_Content_label_encoder_1 = LabelEncoder()
df['Fat_content_encoder'] = Fat_Content_label_encoder_1.fit_transform(df['Item_Fat_Content'])

In [75]:
Item_Type_label_encoder_2 = LabelEncoder()
df['Item_type_encoder'] = Item_Type_label_encoder_2.fit_transform(df['Item_Type'])

In [76]:
Identifier_label_encoder_3 = LabelEncoder()
df['Outlet_Identifier_enocder'] = Identifier_label_encoder_3.fit_transform(df['Outlet_Identifier'])

In [77]:
Establishment_Year_encoder_4 = LabelEncoder()
df['Establishment_Year_encoder'] = Establishment_Year_encoder_4.fit_transform(df['Outlet_Establishment_Year'])

In [78]:
Size_encoder_5 = LabelEncoder()
df['Size_encoder'] = Size_encoder_5.fit_transform(df['Outlet_Size'])

In [79]:
df['Size_encoder']

0       1
1       1
2       1
3       1
4       0
       ..
8518    0
8519    1
8520    2
8521    1
8522    2
Name: Size_encoder, Length: 8523, dtype: int32

In [80]:
Location_Type_encoder_6 = LabelEncoder()
df['Location_type_encoder']  = Location_Type_encoder_6.fit_transform(df['Outlet_Location_Type'])

In [81]:
Outlet_Type_encoder_7 = LabelEncoder()
df['Outlet_type'] = Outlet_Type_encoder_7.fit_transform(df['Outlet_Type'])

In [82]:
x = df[['Fat_content_encoder','Item_type_encoder','Outlet_Identifier_enocder','Establishment_Year_encoder','Size_encoder','Location_type_encoder','Outlet_type']]

In [83]:
x

,Fat_content_encoder,Item_type_encoder,Outlet_Identifier_enocder,Establishment_Year_encoder,Size_encoder,Location_type_encoder,Outlet_type
0,1,4,9,4,1,0,1
1,2,14,3,8,1,2,2
2,1,10,9,4,1,0,1
3,2,6,0,3,1,2,0
4,1,9,1,1,0,2,1
...,...,...,...,...,...,...,...
8518,1,13,1,1,0,2,1
8519,2,0,7,5,1,1,1
8520,1,8,6,6,2,1,1
8521,2,13,3,8,1,2,2
8522,1,14,8,2,2,0,1

In [84]:
x.head(3)

,Fat_content_encoder,Item_type_encoder,Outlet_Identifier_enocder,Establishment_Year_encoder,Size_encoder,Location_type_encoder,Outlet_type
0,1,4,9,4,1,0,1
1,2,14,3,8,1,2,2
2,1,10,9,4,1,0,1

In [85]:
y.head()

0    3735.1380
1     443.4228
2    2097.2700
3     732.3800
4     994.7052
Name: Item_Outlet_Sales, dtype: float64

In [86]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [87]:
from sklearn.ensemble import RandomForestRegressor

In [88]:
model = RandomForestRegressor(n_estimators=100)
model.fit(x_train, y_train)

RandomForestRegressor()

In [89]:
import pickle

In [90]:
# save the model
with open('models/model.pkl','wb') as model_file:
    pickle.dump(model, model_file)

In [91]:
# save all label encoder
with open('models/Fat_Content_label_encoder_1.pkl','wb') as fat_content_file:
    pickle.dump(Fat_Content_label_encoder_1, fat_content_file)

In [92]:
with open('models/Item_Type_label_encoder_2.pkl','wb') as item_type_file:
    pickle.dump(Item_Type_label_encoder_2, item_type_file)

In [93]:
with open('models/Identifier_label_encoder_3.pkl','wb')as identifier_file:
    pickle.dump(Identifier_label_encoder_3, identifier_file)

In [94]:
with open('models/Establishment_Year_encoder_4.pkl','wb') as establishment_year_file:
    pickle.dump(Establishment_Year_encoder_4, establishment_year_file)

In [95]:
with open('models/Size_encoder_5.pkl', 'wb') as size_encoder_file:
    pickle.dump(Size_encoder_5, size_encoder_file)

In [96]:
with open('models/Location_Type_encoder_6.pkl','wb') as size_encoder_file:
    pickle.dump(Location_Type_encoder_6, size_encoder_file)

In [97]:
with open('models/Outlet_Type_encoder_7.pkl','wb') as size_encoder_file:
    pickle.dump(Outlet_Type_encoder_7, size_encoder_file)